import type { Locale } from '../data/content';

const dictionaries = {
  product: ['product', 'продукт', 'platform', 'платформ', 'user', 'користувач'],
  data: ['data', 'дан', 'analytics', 'аналітик', 'metric', 'метрик'],
  ai: ['ai', 'шi', 'ші', 'model', 'модел', 'agent', 'агент'],
  game: ['game', 'гра', 'ігров', 'unity', 'simulation', 'симуляц'],
  language: ['language', 'multilingual', 'мов', 'translation', 'переклад', 'localization', 'локаліз'],
  speed: ['fast', 'швид', 'latency', 'затрим', 'performance', 'продуктив'],
} as const;

type Signal = keyof typeof dictionaries;

export interface StrategyPlan {
  signals: Signal[];
  title: string;
  steps: string[];
  caveat: string;
}

export function buildOfflinePlan(input: string, locale: Locale): StrategyPlan {
  const normalized = input.toLocaleLowerCase(locale);
  const signals = (Object.keys(dictionaries) as Signal[]).filter((signal) =>
    dictionaries[signal].some((keyword) => normalized.includes(keyword)),
  );
  const selected: Signal[] = signals.length > 0 ? signals : ['product'];

  const libraries: Record<Locale, Record<Signal, string>> = {
    en: {
      product: 'Define one user-visible outcome and an evidence boundary before choosing the stack.',
      data: 'Design an event contract, a privacy budget, and one decision the analysis must improve.',
      ai: 'Start with an eval set and a deterministic fallback; make model uncertainty visible in the interface.',
      game: 'Prototype the smallest satisfying loop, then measure input, frame, and state-update budgets.',
      language: 'Model locale parity as a schema constraint and test terminology on real product states.',
      speed: 'Set separate budgets for transfer, main-thread work, render stability, and measured network round-trip.',
    },
    uk: {
      product: 'Спочатку визнач один видимий результат для користувача й межу доказів, а вже потім обирай стек.',
      data: 'Спроєктуй event contract, privacy budget і одне рішення, яке має покращити аналіз.',
      ai: 'Почни з eval-набору й детермінованого fallback; покажи невпевненість моделі в інтерфейсі.',
      game: 'Збери найменший захопливий loop, а потім вимірюй input, frame і state-update budgets.',
      language: 'Зроби locale parity обмеженням схеми та тестуй термінологію на реальних продуктових станах.',
      speed: 'Розділи budgets для transfer, main-thread work, стабільності render і виміряного network round-trip.',
    },
  };

  return {
    signals: selected,
    title: locale === 'en' ? 'Offline horizon map' : 'Офлайн-карта горизонту',
    steps: selected.slice(0, 4).map((signal) => libraries[locale][signal]),
    caveat: locale === 'en'
      ? 'Generated by a deterministic local ruleset—not presented as a language model.'
      : 'Згенеровано детермінованими локальними правилами — це не видається за мовну модель.',
  };
}
