import { useEffect, useRef, useState } from 'react';
import type { Locale } from '../data/content';
import {
  startNeuralField,
  type NeuralFallbackReason,
  type NeuralFieldSnapshot,
} from '../engine/neural-field';

const text = {
  en: {
    kicker: 'WEBGPU / COMPUTE SHADER / DETERMINISTIC MLP',
    title: 'Neural particle field',
    intro: 'Run a fixed 4→8→4 neural network across thousands of particles. WebGPU performs the inference and rendering; a JavaScript reference checks the first GPU result and becomes the visible fallback when needed.',
    batch: 'Particle batch',
    run: 'Rebuild neural field',
    running: 'NEGOTIATING GPU…',
    canvasLabel: 'Animated particle field generated by a deterministic 4 by 8 by 4 neural network',
    cpuReference: 'CPU reference',
    cpuSubmit: 'CPU encode + submit',
    gpuCompute: 'GPU compute',
    gpuRender: 'GPU render',
    maxError: 'Max |GPU − CPU|',
    unavailableMetric: 'N/A',
    precisionPending: '—',
    timestampOn: 'TIMESTAMP QUERY / ACTIVE',
    timestampOff: 'GPU TIME / NOT CLAIMED',
    reduced: 'Reduced-motion is active: the field renders one static frame.',
    architecture: 'FIXED WEIGHTS / 4 INPUTS / 8 TANH HIDDEN UNITS / 4 OUTPUTS / FIRST FRAME READBACK',
    modes: {
      negotiating: 'NEURAL FIELD / NEGOTIATING',
      webgpu: 'NEURAL FIELD / WEBGPU LIVE',
      canvas: 'NEURAL FIELD / JS + CANVAS',
      static: 'NEURAL FIELD / STATIC FALLBACK',
      error: 'NEURAL FIELD / UNAVAILABLE',
    },
    reasons: {
      'webgpu-unavailable': 'WebGPU is unavailable here. The same fixed network is running in JavaScript and rendering through Canvas 2D.',
      'webgpu-failed': 'WebGPU negotiation or shader validation failed. The deterministic JavaScript/Canvas path is active.',
      'device-lost': 'The GPU device was lost. Resources were released and the deterministic JavaScript/Canvas path took over.',
    },
  },
  uk: {
    kicker: 'WEBGPU / COMPUTE SHADER / ДЕТЕРМІНОВАНА MLP',
    title: 'Нейронне поле частинок',
    intro: 'Запусти фіксовану нейромережу 4→8→4 для тисяч частинок. WebGPU виконує inference і rendering; JavaScript reference перевіряє перший GPU-результат і стає видимим fallback за потреби.',
    batch: 'Кількість частинок',
    run: 'Перебудувати нейрополе',
    running: 'УЗГОДЖЕННЯ GPU…',
    canvasLabel: 'Анімоване поле частинок, створене детермінованою нейромережею чотири на вісім на чотири',
    cpuReference: 'CPU reference',
    cpuSubmit: 'CPU encode + submit',
    gpuCompute: 'GPU compute',
    gpuRender: 'GPU render',
    maxError: 'Макс. |GPU − CPU|',
    unavailableMetric: 'Н/Д',
    precisionPending: '—',
    timestampOn: 'TIMESTAMP QUERY / АКТИВНИЙ',
    timestampOff: 'GPU-ЧАС / НЕ ЗАЯВЛЕНО',
    reduced: 'Увімкнено reduced-motion: поле рендерить один статичний кадр.',
    architecture: 'ФІКСОВАНІ ВАГИ / 4 ВХОДИ / 8 TANH-НЕЙРОНІВ / 4 ВИХОДИ / READBACK ПЕРШОГО КАДРУ',
    modes: {
      negotiating: 'НЕЙРОПОЛЕ / УЗГОДЖЕННЯ',
      webgpu: 'НЕЙРОПОЛЕ / WEBGPU LIVE',
      canvas: 'НЕЙРОПОЛЕ / JS + CANVAS',
      static: 'НЕЙРОПОЛЕ / СТАТИЧНИЙ FALLBACK',
      error: 'НЕЙРОПОЛЕ / НЕДОСТУПНЕ',
    },
    reasons: {
      'webgpu-unavailable': 'WebGPU тут недоступний. Та сама фіксована мережа працює в JavaScript і рендерить через Canvas 2D.',
      'webgpu-failed': 'Узгодження WebGPU або валідація shader не вдалися. Активний детермінований шлях JavaScript/Canvas.',
      'device-lost': 'GPU device втрачено. Ресурси звільнено, а детермінований шлях JavaScript/Canvas перебрав роботу.',
    },
  },
} satisfies Record<Locale, {
  kicker: string;
  title: string;
  intro: string;
  batch: string;
  run: string;
  running: string;
  canvasLabel: string;
  cpuReference: string;
  cpuSubmit: string;
  gpuCompute: string;
  gpuRender: string;
  maxError: string;
  unavailableMetric: string;
  precisionPending: string;
  timestampOn: string;
  timestampOff: string;
  reduced: string;
  architecture: string;
  modes: Record<NeuralFieldSnapshot['mode'], string>;
  reasons: Record<NeuralFallbackReason, string>;
}>;

const initialSnapshot: NeuralFieldSnapshot = {
  mode: 'negotiating',
  metrics: null,
  reducedMotion: false,
};

function milliseconds(value: number | null | undefined, empty: string): string {
  return value === null || value === undefined ? empty : `${value.toFixed(3)} ms`;
}

export default function NeuralField({ locale }: { locale: Locale }) {
  const c = text[locale];
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const fallbackCanvasRef = useRef<HTMLCanvasElement>(null);
  const [requestedBatch, setRequestedBatch] = useState(16_384);
  const [run, setRun] = useState({ batchSize: 16_384, revision: 0 });
  const [snapshot, setSnapshot] = useState<NeuralFieldSnapshot>(initialSnapshot);

  useEffect(() => {
    const canvas = canvasRef.current;
    const fallbackCanvas = fallbackCanvasRef.current;
    if (!canvas || !fallbackCanvas) return;

    let disposed = false;
    let stop: (() => void) | undefined;
    setSnapshot(initialSnapshot);
    void startNeuralField(canvas, {
      batchSize: run.batchSize,
      fallbackCanvas,
      onSnapshot: (nextSnapshot) => {
        if (!disposed) setSnapshot(nextSnapshot);
      },
    }).then((cleanup) => {
      if (disposed) cleanup();
      else stop = cleanup;
    });

    return () => {
      disposed = true;
      stop?.();
    };
  }, [run]);

  const metrics = snapshot.metrics;
  const ready = snapshot.mode !== 'negotiating' && snapshot.mode !== 'error';
  const gpuMetricEmpty = metrics?.timestampQuery ? c.precisionPending : c.unavailableMetric;

  return (
    <div className="module-grid">
      <div className="module-copy">
        <p className="module-kicker">{c.kicker}</p>
        <h3>{c.title}</h3>
        <p>{c.intro}</p>
        <label className="range-control">
          <span>
            {c.batch}
            <strong>{requestedBatch.toLocaleString(locale)}</strong>
          </span>
          <input
            type="range"
            min="4096"
            max="65536"
            step="4096"
            value={requestedBatch}
            onChange={(event) => setRequestedBatch(Number(event.target.value))}
          />
        </label>
        <button
          className="module-action"
          type="button"
          disabled={snapshot.mode === 'negotiating'}
          onClick={() => setRun((current) => ({
            batchSize: requestedBatch,
            revision: current.revision + 1,
          }))}
        >
          {snapshot.mode === 'negotiating' ? c.running : c.run}
          <span aria-hidden="true">↗</span>
        </button>
        <p className="module-disclaimer">{c.architecture}</p>
        {snapshot.reducedMotion && <p className="module-warning">{c.reduced}</p>}
      </div>

      <div className="science-card" aria-live="polite">
        <div className="telemetry-head">
          <span>{c.modes[snapshot.mode]}</span>
          <i className={ready ? 'is-ready' : ''} />
        </div>
        <div className="neural-viewport">
          <canvas
            className="neural-canvas"
            ref={canvasRef}
            role="img"
            aria-label={c.canvasLabel}
            hidden={snapshot.mode === 'canvas' || snapshot.mode === 'static' || snapshot.mode === 'error'}
          >
            {c.canvasLabel}
          </canvas>
          <canvas
            className="neural-canvas"
            ref={fallbackCanvasRef}
            role="img"
            aria-label={c.canvasLabel}
            hidden={snapshot.mode !== 'canvas' && snapshot.mode !== 'static' && snapshot.mode !== 'error'}
          >
            {c.canvasLabel}
          </canvas>
          {snapshot.reason && (
            <p
              className="module-warning"
              style={{
                background: 'rgba(9, 11, 16, .92)',
                bottom: 12,
                left: 12,
                margin: 0,
                position: 'absolute',
                right: 12,
              }}
            >
              {c.reasons[snapshot.reason]}
            </p>
          )}
        </div>
        <dl className="science-metrics">
          <div>
            <dt>{c.cpuReference}</dt>
            <dd>{milliseconds(metrics?.cpuReferenceMs, c.precisionPending)}</dd>
          </div>
          <div>
            <dt>{c.cpuSubmit}</dt>
            <dd>{milliseconds(metrics?.cpuSubmitMs, c.unavailableMetric)}</dd>
          </div>
          <div>
            <dt>{c.gpuCompute}</dt>
            <dd>{milliseconds(metrics?.gpuComputeMs, gpuMetricEmpty)}</dd>
          </div>
          <div>
            <dt>{c.gpuRender}</dt>
            <dd>{milliseconds(metrics?.gpuRenderMs, gpuMetricEmpty)}</dd>
          </div>
          <div>
            <dt>{c.maxError}</dt>
            <dd>{metrics?.maxAbsoluteError === null || metrics?.maxAbsoluteError === undefined
              ? c.unavailableMetric
              : metrics.maxAbsoluteError.toExponential(2)}</dd>
          </div>
        </dl>
        <p className="telemetry-foot">
          {metrics?.timestampQuery ? c.timestampOn : c.timestampOff}
        </p>
      </div>
    </div>
  );
}
