// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     criomant:horizon@0.1.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
	"unsafe"
	"wit_component/export_criomant_horizon_checksum"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, 0, 1))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport criomant:horizon/checksum@0.1.0#hash
func wasm_export_criomant_horizon_checksum_hash(arg0 uintptr, arg1 uint32) int32 {

	value := unsafe.Slice((*uint32)(unsafe.Pointer(arg0)), arg1)
	witRuntime.Unpin()
	result := export_criomant_horizon_checksum.Hash(value)
	return int32(result)

}

// Unused, but present to make the compiler happy
func main() {}
